<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fc1b4f01-2493-4ec5-ac68-ad8ae74f83ed</elementGuidId>
    <imagePath></imagePath>
    <name>div_highcharts_8qxikzm_0</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[6]/div[1]/div[4]/div[2]/div[1]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#highcharts-8qxikzm-0</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'highcharts-8qxikzm-0') and equals(@class,'highcharts-container ')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>highcharts-container </value>
        <webElementGuid>ca600605-2a09-475f-adb2-90e09e485902</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>highcharts-8qxikzm-0</value>
        <webElementGuid>ec827d62-2ef0-410f-aa58-c542a95c29b5</webElementGuid>
    </webElementProperties>
</WebElementEntity>