<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c10676d1-5b92-44a3-839a-ca5bb4a40d77</elementGuidId>
    <imagePath></imagePath>
    <name>div_highcharts_ndq9k7g_0</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[6]/div[1]/div[4]/div[2]/div[1]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#highcharts-ndq9k7g-0</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'highcharts-ndq9k7g-0') and equals(@class,'highcharts-container ')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>highcharts-container </value>
        <webElementGuid>5d19d919-2a58-4e9a-a37f-e90b173923e5</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>highcharts-ndq9k7g-0</value>
        <webElementGuid>253c6660-f51f-46e8-ad51-9da098669862</webElementGuid>
    </webElementProperties>
</WebElementEntity>