<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>dcac7c2e-f252-4a31-927c-5aa2ff81dfc9</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_javascript</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[2]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[data-toggle='right-sidebar']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'dropdown-toggle no-arrow')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>dropdown-toggle no-arrow</value>
        <webElementGuid>25ef5193-df8e-4088-9980-8859bd6f5e37</webElementGuid>
    </webElementProperties>
</WebElementEntity>