<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>17ebdf74-a5bc-46e1-8cb2-50f165e6d747</elementGuidId>
    <imagePath></imagePath>
    <name>div_calendar_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[6]/div[1]/div[1]/div[2]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#calendar</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'calendar') and equals(@class,'fc fc-bootstrap4 fc-ltr')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>fc fc-bootstrap4 fc-ltr</value>
        <webElementGuid>d90b2716-9cec-45a5-a9eb-583b02bf4ecb</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>calendar</value>
        <webElementGuid>93ffc976-e71b-4583-a4db-1ec08b698750</webElementGuid>
    </webElementProperties>
</WebElementEntity>