<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>54c426ff-717b-4749-9154-882f3087b7d5</elementGuidId>
    <imagePath></imagePath>
    <name>div_calendar</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[6]/div[1]/div[1]/div[2]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#calendar</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'calendar') and equals(@class,'fc fc-bootstrap4 fc-ltr')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>fc fc-bootstrap4 fc-ltr</value>
        <webElementGuid>a1c8365a-b124-4849-8fc3-1853e9fdd553</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>calendar</value>
        <webElementGuid>e0724055-8b79-417a-aff0-3edf23622947</webElementGuid>
    </webElementProperties>
</WebElementEntity>