<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_calendar</name>
   <tag></tag>
   <elementGuidId>54c426ff-717b-4749-9154-882f3087b7d5</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[6]/div[1]/div[1]/div[2]/div[1]/div[122321909]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@id,'calendar') and equals(@class,'fc fc-bootstrap4 fc-ltr')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#calendar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fc fc-bootstrap4 fc-ltr</value>
      <webElementGuid>e6308052-582a-4d8f-9ba7-e9b36b5e9668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calendar</value>
      <webElementGuid>0e973ca4-359c-46f7-bb5e-fca8ed4d5e20</webElementGuid>
   </webElementProperties>
</WebElementEntity>
