<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c4c04219-cc10-4c4b-8016-e8fa9b53ec87</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_sitemap_html</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[4]/div[2]/div[1]/div[1]/div[1]/ul[1]/li[12]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.dropdown-toggle.active</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'dropdown-toggle no-arrow active')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>dropdown-toggle no-arrow active</value>
        <webElementGuid>f0d32122-22f3-430d-8702-380b842e8f8a</webElementGuid>
    </webElementProperties>
</WebElementEntity>