<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>841f6d8b-b437-4e98-ae29-6afbb94deab4</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_sitemap_html</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[4]/div[2]/div[1]/div[1]/div[1]/ul[1]/li[12]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.dropdown-toggle.active</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'dropdown-toggle no-arrow active')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>dropdown-toggle no-arrow active</value>
        <webElementGuid>f20753ba-5e0b-4a27-9e78-d71e6798d572</webElementGuid>
    </webElementProperties>
</WebElementEntity>