<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2deb5863-a83e-4d9f-9e54-6dc73c1c55b2</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_sitemap_html</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[4]/div[2]/div[1]/div[1]/div[1]/ul[1]/li[12]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.dropdown-toggle.active</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'dropdown-toggle no-arrow active')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>dropdown-toggle no-arrow active</value>
        <webElementGuid>f4b415c7-fe6e-406e-b5f4-44bb97f1e761</webElementGuid>
    </webElementProperties>
</WebElementEntity>