<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>21fde37b-f459-468f-b26e-85741a31c97d</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_invoice_html</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[4]/div[2]/div[1]/div[1]/div[1]/ul[1]/li[14]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.dropdown-toggle.active</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'dropdown-toggle no-arrow active')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>dropdown-toggle no-arrow active</value>
        <webElementGuid>006bd87e-06fc-4503-8655-d5a59abfbc0f</webElementGuid>
    </webElementProperties>
</WebElementEntity>