<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3455c21a-704b-4272-9104-fafc2e3e5e8e</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_invoice_html</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[4]/div[2]/div[1]/div[1]/div[1]/ul[1]/li[14]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.dropdown-toggle.active</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'dropdown-toggle no-arrow active')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>dropdown-toggle no-arrow active</value>
        <webElementGuid>286f8b4a-9bec-45d7-b437-5e30c0374140</webElementGuid>
    </webElementProperties>
</WebElementEntity>